export const SET_CART_ITEMS_SUCCESSFUL = "SET_CART_ITEMS_SUCCESSFUL";
export const SET_CART_ITEMS_PROCESSING = "SET_CART_ITEMS_PROCESSING";
export const STOP_SET_CART_ITEMS_PROCESSING = "STOP_SET_CART_ITEMS_PROCESSING";
