export const GET_CATEGORY_SUCCESSFUL = "GET_CATEGORY_SUCCESSFUL";
export const GET_CATEGORY_PROCESSING = "GET_CATEGORY_PROCESSING";
export const STOP_GET_CATEGORY_PROCESSING = "STOP_GET_CATEGORY_PROCESSING";
