export const GET_PRODUCTS_SUCCESSFUL = "GET_PRODUCTS_SUCCESSFUL";
export const GET_PRODUCTS_PROCESSING = "GET_PRODUCTS_PROCESSING";
export const STOP_GET_PRODUCTS_PROCESSING = "STOP_GET_PRODUCTS_PROCESSING";
