export const GET_SUB_CATEGORY_SUCCESSFUL = "GET_SUB_CATEGORY_SUCCESSFUL";
export const GET_SUB_CATEGORY_PROCESSING = "GET_SUB_CATEGORY_PROCESSING";
export const STOP_GET_SUB_CATEGORY_PROCESSING =
  "STOP_GET_SUB_CATEGORY_PROCESSING";
